-- VISTA TAVOLI prenotati --

CREATE OR REPLACE VIEW tavoli_prenotati AS
SELECT ORDINE.NumTavolo, ORDINE.DataOraOrdine
FROM ( ORDINE join CLIENTEPRENOTANTE on ORDINE.DataOraOrdine = CLIENTEPRENOTANTE.DataOraAssegnati )
WHERE exists (SELECT CLIENTEPRENOTANTE.NumTavoloAssegnato, CLIENTEPRENOTANTE.DataOraAssegnati
	      FROM CLIENTEPRENOTANTE
	      WHERE ORDINE.DataOraOrdine = CLIENTEPRENOTANTE.DataOraAssegnati)	
ORDER BY ORDINE.DataOraOrdine;